version: '2'

services:

  web:
    restart: always
    build: ./web/
    container_name: web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: env
    volumes:
      - ./web:/data/web
    command: >
      /bin/sh -c "./manage.py makemigrations articles &&
      ./manage.py migrate &&
      echo yes | ./manage.py collectstatic &&
      echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')\" | ./manage.py shell &&
      gunicorn blog.wsgi:application -w 2 -b :8000"

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    # build: ./postgres/
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backups:/backup
    env_file:
      - env
    ports:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
