version: '3'

volumes:
  postgres_dev_data:
  postgres_dev_backup:

services:

  postgres:
    container_name: blog_postgres
    network_mode: "bridge"
    build:
      context: ./dockerfiles/postgres/
    image: blog-postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - postgres_dev_backup:/backups
      - ./dockerfiles/postgres/dump/:/docker-entrypoint-initdb.d/
    env_file: env/postgres.env

  django:
    container_name: blog_django
    network_mode: "bridge"
    depends_on:
      - postgres
    links:
      - postgres
    env_file: env/django.env
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    image: blog-django:latest
    user: django
    command: /start_dev.sh
    volumes:
      - .:/code
      - ./public:/code/public
    ports:
      - "8000:8000"
