version: '3'

services:
  web:
    env_file:
      - .env
    build: .
    container_name: 'django-blog'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/blog-project
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    env_file:
      - .env
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

volumes:
  pgdata:
